# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbaa56e6009627401c492dfdc44ac408cfd9b3b44eda11fed3bdcfa84d4a42a7bd1f01457a8ccc4489f2b0824b7e23fa56e23a25b13ae463131fc0a094e6e7a0

test:
  secret_key_base: d08565159281661b0134e2260cb11ef24f21961602ea3895aab6221a139b788293a6c6333cff692b061c48dcb3f550a44768220823a18cf18a1bd861c81a2cbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
